# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status Post', 'verbose_name_plural': 'Status Posts'},
        ),
    ]
