# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190211_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
